### ISSUE TITLE
Multiple languages?

### ISSUE THREAD

**Issue by lanndoan** [techstreams/TSFormTranslator#2]
Hi - I'm trying to use your instructions here (https://techstreams.github.io/TSFormTranslator/) to translate a short google survey into multiple languages. I envision, like a drop down list of the languages in the upper right, people can select the language, and then the form is translated. Similar to the google translating of websites (which isn't perfect) but for google forms.

I don't have experience in HTML, if it's something you are able to assist with. The form would be use by low-English proficient and low-tech users -- so looking for straightforward translation of the form.

Thanks!

**Comment by techstreams** [comment]
Hi @lanndoan - Thank you for your interest in the project.  Glad you find it useful.  

Unfortunately, this project only supports one language translation at a time and I'm not able to update it to accommodate more at this current time.
